// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ympXyOZifoncAgh7aoKrFaDDyeFexJA',
    appId: '1:296684920280:web:649f455fd4f9ca944fe6ad',
    messagingSenderId: '296684920280',
    projectId: 'poultry-76bef',
    authDomain: 'poultry-76bef.firebaseapp.com',
    storageBucket: 'poultry-76bef.appspot.com',
    measurementId: 'G-GCK7VRSYRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDptfAEBr3jQtuM7V4VuckkY-4U0DU2EI8',
    appId: '1:296684920280:android:576d45c9d0428dca4fe6ad',
    messagingSenderId: '296684920280',
    projectId: 'poultry-76bef',
    storageBucket: 'poultry-76bef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJEkWEJGNPzJK5U4Nvgn18-UqtbIrLLTI',
    appId: '1:296684920280:ios:e2f59ce08e3dec6b4fe6ad',
    messagingSenderId: '296684920280',
    projectId: 'poultry-76bef',
    storageBucket: 'poultry-76bef.appspot.com',
    iosBundleId: 'com.example.poultryPalSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJEkWEJGNPzJK5U4Nvgn18-UqtbIrLLTI',
    appId: '1:296684920280:ios:652b3f78507fb9084fe6ad',
    messagingSenderId: '296684920280',
    projectId: 'poultry-76bef',
    storageBucket: 'poultry-76bef.appspot.com',
    iosBundleId: 'com.example.poultryPalSeller.RunnerTests',
  );
}
